name = "chess-hotspot"
compatibility_date = "2025-06-01"
pages_build_output_dir = "./out"

# main = "src/index.ts" 

#[assets]
#bucket = "./out"
#binding = "ASSETS"

[[kv_namespaces]]
binding = "SPOTS_KV"
id = "2dd0b728d5db4613b3908f3b7267a6df"
preview_id = "af5424dc76974423bbdfb6017f03aeb4"

