name = "chess-hotspot"
compatibility_date = "2025-06-01"
pages_build_output_dir = "./out"

[vars]
NEXT_PUBLIC_MAP_STYLE = "https://basemaps.cartocdn.com/gl/voyager-gl-style/style.json"

[[kv_namespaces]]
binding = "SPOTS_KV"
id = "2dd0b728d5db4613b3908f3b7267a6df"
preview_id = "af5424dc76974423bbdfb6017f03aeb4"

